// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignInService.Data;

#nullable disable

namespace SignInUserService.Migrations
{
    [DbContext(typeof(SignInDbContext))]
    partial class SignInDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SignInService.Models.PotentialCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentOTPValidationAttempt")
                        .HasColumnType("int");

                    b.Property<bool?>("IsOTPValidated")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OTP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OTPGenAttemptForMobileNumberCount")
                        .HasColumnType("int");

                    b.Property<int?>("OTPGenAttemptForPublicIpCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("OtpExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublicIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PotentialCustomer");
                });
#pragma warning restore 612, 618
        }
    }
}
